Repository prob-ml/bliss, pull requests merged in 2021-01, with the labels that each got.

#173 Ignore deprecation warning in `tests/test_tune.py`
  pytest.ini
Labels: tests

#139 Im/kl qp sleep encoder
  .github/workflows/config.yml
  .gitignore
  bliss/datasets/simulated.py
  bliss/models/decoder.py
  bliss/models/encoder.py
  bliss/models/galaxy_net.py
  bliss/sleep.py
  bliss/wake.py
  config/model/m2.yaml
  config/model/sleep_1galaxy_1star.yaml
  config/model/sleep_galaxy_3_centered.yaml
  config/model/sleep_galaxy_basic.yaml
  config/model/sleep_galaxy_one_tile.yaml
  config/model/sleep_star_basic.yaml
  config/model/sleep_star_one_tile.yaml
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_configs.py
  tests/test_encoder_forward.py
  tests/test_kl_pq.py
  tests/test_tune.py
  tests/test_wake.py
Labels: enhancement

#200 Github pages
  docs/.buildinfo
  docs/.nojekyll
  docs/_modules/bliss/datasets/catsim.html
  docs/_modules/bliss/datasets/sdss.html
  docs/_modules/bliss/datasets/simulated.html
  docs/_modules/bliss/models/decoder.html
  docs/_modules/bliss/models/encoder.html
  docs/_modules/bliss/models/galaxy_net.html
  docs/_modules/bliss/sleep.html
  docs/_modules/bliss/wake.html
  docs/_modules/index.html
  docs/_sources/api/bliss.datasets.rst.txt
  docs/_sources/api/bliss.models.rst.txt
  docs/_sources/api/bliss.rst.txt
  docs/_sources/api/index.rst.txt
  docs/_sources/api/modules.rst.txt
  docs/_sources/index.rst.txt
  docs/_static/alabaster.css
  docs/_static/basic.css
  docs/_static/custom.css
  docs/_static/doctools.js
  docs/_static/documentation_options.js
  docs/_static/file.png
  docs/_static/jquery-3.5.1.js
  docs/_static/jquery.js
  docs/_static/language_data.js
  docs/_static/minus.png
  docs/_static/plus.png
  docs/_static/pygments.css
  docs/_static/searchtools.js
  docs/_static/underscore-1.3.1.js
  docs/_static/underscore.js
  docs/api/bliss.datasets.html
  docs/api/bliss.html
  docs/api/bliss.models.html
  docs/api/index.html
  docs/api/modules.html
  docs/genindex.html
  docs/index.html
  docs/objects.inv
  docs/py-modindex.html
  docs/search.html
  docs/searchindex.js
  docsrc/Makefile
  docsrc/api/bliss.datasets.rst
  docsrc/api/bliss.models.rst
  docsrc/api/bliss.rst
  docsrc/api/index.rst
  docsrc/api/modules.rst
  docsrc/conf.py
  docsrc/index.rst
  docsrc/make.bat
Labels: documentation
