Repository prob-ml/bliss, pull requests merged in 2021-03, with the labels that each got.

#225 Evaluation of sleep_net on SDSS
  .gitignore
  .pre-commit-config.yaml
  bliss/datasets/galsim_galaxies.py
  bliss/datasets/sdss.py
  bliss/datasets/simulated.py
  bliss/metrics.py
  bliss/models/decoder.py
  bliss/models/encoder.py
  bliss/models/fnp.py
  bliss/plotting.py
  bliss/predict.py
  bliss/sleep.py
  bliss/tune.py
  bliss/utils.py
  bliss/wake.py
  case_studies/README.md
  case_studies/sdss_galaxies/README.md
  case_studies/sdss_galaxies/sdss_galaxies.ipynb
  case_studies/sdss_galaxies/sparse_field_lib.py
  case_studies/starnet/plotting.py
  docs/docsrc/conf.py
  pyproject.toml
  tests/conftest.py
  tests/test_encoder_forward.py
  tests/test_fnp.py
  tests/test_kl_pq.py
  tests/test_plotting.py
  tests/test_wake.py
Labels: case study

#227 Place decoder tile construction functionality into Tiler class
  bliss/models/decoder.py
Labels: refactoring

#234 Separate SDSS Stamping code into StarStamper class
  bliss/datasets/sdss.py
Labels: refactoring

#233 Im/sdss like galaxies
  .gitattributes
  .pre-commit-config.yaml
  bliss/datasets/galsim_galaxies.py
  bliss/generate.py
  bliss/models/galaxy_net.py
  bliss/train.py
  case_studies/sdss_galaxies/sdss_dataset.ipynb
  case_studies/sdss_galaxies/sdss_results.ipynb
  config/dataset/saved_galaxies.yaml
  config/dataset/sdss_galaxies.yaml
  config/dataset/toy_gaussian.yaml
  config/generate/sdss_galaxies.yaml
  config/model/galaxy_net.yaml
  data/OneDegSq.fits
  data/cosmoDC2_wld_sdss_10_sq_deg.fits
  data/gold_dc2_catalog.fits
  data/gold_sdss_galaxy_images.pt
  data/sdss/94/1/12/fpM-000094-g1-0012.fits
  data/sdss/94/1/12/fpM-000094-i1-0012.fits
  data/sdss/94/1/12/fpM-000094-r1-0012.fits
  data/sdss/94/1/12/fpM-000094-u1-0012.fits
  data/sdss/94/1/12/fpM-000094-z1-0012.fits
  data/sdss/94/1/12/frame-g-000094-1-0012.fits
  data/sdss/94/1/12/frame-i-000094-1-0012.fits
  data/sdss/94/1/12/frame-r-000094-1-0012.fits
  data/sdss/94/1/12/frame-u-000094-1-0012.fits
  data/sdss/94/1/12/frame-z-000094-1-0012.fits
  data/sdss/94/1/12/photoObj-000094-1-0012.fits
  data/sdss/94/1/12/psField-000094-1-0012.fits
  data/sdss/94/1/photoField-000094-1.fits
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_sdss_galsim_galaxies.py
Labels: feature
